2024-02-13 11:17:21,017 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2024-02-13 11:17:21,018 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2024-02-13 11:17:21,019 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "hardiksharmah73@gmail.com", --configuration: "default", --format: "value(name)", PROJECT_ID_OR_NUMBER: "pegasus-401519"]
2024-02-13 11:17:21,027 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-02-13 11:17:22,313 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17294043a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-02-13 11:17:22,313 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/pegasus-401519?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17294043a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-02-13 11:17:24,484 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-02-13 11:17:25,352 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17294043d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-02-13 11:17:25,353 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/pegasus-401519?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17294043d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-02-13 11:17:29,681 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-02-13 11:17:31,235 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/pegasus-401519?alt=json HTTP/1.1" 200 None
2024-02-13 11:17:31,238 DEBUG    root            Chosen display Format:default value(name)
2024-02-13 11:17:31,239 INFO     root            Display format: "default value(name)"
2024-02-13 11:17:31,240 INFO     ___FILE_ONLY___ PEGASUS

